# Generated by Django 4.1.4 on 2022-12-21 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('IdAutor', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.IntegerField()),
                ('Nacionalidad', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('IdLibro', models.IntegerField(primary_key=True, serialize=False)),
                ('Codigo', models.IntegerField()),
                ('Titulo', models.TextField()),
                ('ISBN', models.TextField()),
                ('Editorial', models.TextField()),
                ('NumPags', models.TextField()),
                ('IdAutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('IdPrestamo', models.IntegerField(primary_key=True, serialize=False)),
                ('IdUsuario', models.IntegerField()),
                ('FecPrestamo', models.DateField()),
                ('FecDevolucion', models.DateField()),
                ('IdLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('IdUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('NumUsuario', models.IntegerField()),
                ('NIF', models.TextField()),
                ('Nombre', models.TextField()),
                ('Direccion', models.TextField()),
                ('Telefono', models.TextField()),
                ('IdPrestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.prestamos')),
            ],
        ),
    ]
