# Generated by Django 4.1.4 on 2022-12-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_autor_idautor_alter_libro_idlibro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='Nombre',
            field=models.TextField(),
        ),
    ]
