# Generated by Django 4.1.4 on 2022-12-21 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_remove_usuario_idprestamo_alter_prestamos_idusuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelTable(
            name='autor',
            table='Autor',
        ),
    ]
