# Generated by Django 4.1.4 on 2022-12-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_alter_autor_options_alter_autor_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.AlterModelOptions(
            name='prestamos',
            options={'verbose_name': 'Prestamo', 'verbose_name_plural': 'Prestamos'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='libro',
            name='NumPags',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='libro',
            table='Libro',
        ),
        migrations.AlterModelTable(
            name='prestamos',
            table='Prestamos',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='Usuario',
        ),
    ]
