# Generated by Django 4.1.4 on 2022-12-21 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_alter_libro_options_alter_prestamos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prestamos',
            table='Prestamo',
        ),
    ]
